services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - tempo
      - loki
      - alloy     
    restart: always
    networks:
      - monitoring    

  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - ./tempo/data:/var/tempo/traces
    ports:
      - "3200:3200"
      - "4317:4317"   # otlp grpc
      - "4318:4318"   # otlp http
      - "9095:9095"
    restart: always
    networks:
      - monitoring    

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-config.yaml"]
    volumes:
      - ./otel/otel-config.yaml:/etc/otel-config.yaml
    ports:
      - "4319:4317"  # OTLP gRPC (porta externa diferente)
      - "4320:4318"  # OTLP HTTP (porta externa diferente)
    restart: always
    depends_on:
      - tempo
    networks:
      - monitoring    

  loki:
    image: grafana/loki:2.9.1
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml
    ports:
      - "3100:3100"   # porta padrão do Loki para HTTP API
    restart: always
    networks:
      - monitoring

  alloy:
    image: grafana/alloy:latest
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy
    command: run /etc/alloy/config.alloy  --server.http.listen-addr=0.0.0.0:12345
    ports:
      - "12345:12345"   # porta padrão do Loki para HTTP API    
      - "9999:9999" 
    restart: always
    depends_on:
      - loki
    networks:
      - monitoring  

  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-remote-write-receiver'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/targets/example-service.json:/etc/prometheus/example-service.json
      - ./prometheus/data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring       

volumes:
  grafana-storage:

networks:
  monitoring:
    driver: bridge
